import test from 'node:test';
import assert from 'node:assert/strict';
import {makeDemo,freeScoreSVG,validateProject} from '../public/music.mjs';
import {lyricRanges} from '../public/lyric-ranges.mjs';
import {timelineLyrics,lyricRows,retimeLyric} from '../public/lyric-score.mjs';
const fixture=()=>validateProject({...makeDemo(),bpm:60,notes:[{id:'a',midi:60,start:0,duration:1,lyric:''},{id:'b',midi:62,start:1,duration:1,lyric:''},{id:'c',midi:64,start:4,duration:1,lyric:''}],lyrics:[{id:'word',text:'唱',start:0,end:2,noteIds:['a','b'],reviewed:true}]});
test('automatic lyric analysis selects saved vocal blocks and needs no numeric range',()=>{const p=fixture();p.sections=[{id:'intro',source:'other',audioStart:0,audioEnd:2},{id:'v1',source:'vocals',name:'人声1',audioStart:2,audioEnd:5},{id:'v2',source:'vocals',name:'人声2',audioStart:7,audioEnd:9}];assert.deepEqual(lyricRanges(p,10).map(r=>[r.from,r.to]),[[2,5],[7,9]]);assert.deepEqual(lyricRanges(p,10,{mode:'v2'}).map(r=>[r.from,r.to]),[[7,9]]);assert.equal(lyricRanges(p,10,{mode:'whole'})[0].to,10);assert.equal(lyricRanges({...p,sections:[]},10)[0].from,0);assert.throws(()=>lyricRanges(p,10,{manual:true,from:5,to:2}),/范围/);assert.equal(lyricRanges(p,10,{manual:true,from:1,to:2})[0].to,2);});
test('only lyric-bearing rows reserve a track; overlapping words get separate lanes',()=>{const p=fixture(),rows=lyricRows(p,[0,4,8,12]);assert.deepEqual(rows.map(r=>r.height),[92,68,68]);p.lyrics.push({id:'second',text:'字',start:1,end:3,noteIds:['b'],reviewed:true});assert.equal(lyricRows(p,[0,4,8])[0].height,116);const svg=freeScoreSVG(p,{beatsPerRow:4});assert.match(svg,/data-row-ys=/);assert.match(svg,/class="score-lyric-bar/);assert.match(svg,/data-lyric-resize="start"/);assert.match(svg,/data-lyric-resize="end"/);});
test('lyric dragging keeps raw seconds and remaps only the edited word under nonlinear timing',()=>{const p=fixture();p.timeAnchors=[{beat:0,second:0},{beat:2,second:4},{beat:8,second:10}];const t=p.lyrics[0];const updated=retimeLyric(p,t,2,4);assert.deepEqual(updated.noteIds,['b']);assert.equal(updated.start,2);assert.equal(updated.end,4);assert.equal(p.notes[1].duration,1);assert.equal(t.start,0);assert.throws(()=>retimeLyric(p,t,2,2.001),/最短/);assert.throws(()=>retimeLyric(p,t,2,5,{maxSeconds:4}),/原音/);assert.equal(timelineLyrics({...p,lyrics:[updated]})[0].beatStart,1);});
test('legacy lyric text is editable as a strip and lyrics can extend beyond the last note',()=>{const p=fixture();p.lyrics=[];p.notes[0].lyric='旧';assert.equal(timelineLyrics(p)[0].legacyNoteId,'a');p.lyrics=[{id:'manual',text:'新',start:0,end:1,noteIds:['a'],reviewed:true},{id:'late',text:'末',start:10,end:11,noteIds:[],reviewed:false}];assert.ok(!timelineLyrics(p).some(t=>t.legacyNoteId==='a'));const svg=freeScoreSVG(p,{beatsPerRow:4});assert.match(svg,/data-row-starts="0,4,8,12"/);assert.match(svg,/歌词：末/);});

test('editing legacy words preserves nearby text even when the edited timing overlaps it',()=>{const p=fixture();p.notes[2].lyric='后';const tokens=timelineLyrics(p),updated=retimeLyric(p,tokens[0],0,5),next=validateProject({...p,notes:p.notes.map(n=>({...n,lyric:''})),lyrics:tokens.map(t=>t.id===updated.id?updated:t)}),restored=validateProject(JSON.parse(JSON.stringify(next)));assert.deepEqual(timelineLyrics(restored).map(t=>t.text),['唱','后']);assert.deepEqual(restored.notes.map(n=>[n.start,n.duration]),p.notes.map(n=>[n.start,n.duration]));assert.equal(lyricRows(restored,[0,8])[0].height,116);});
