import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {PassThrough} from 'node:stream';
import {mkdtemp,mkdir,writeFile,readFile,readdir,rm} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {singingService,validateSingingWords} from '../src/singing-service.mjs';
const request=body=>({method:'POST',headers:{'x-studio-token':'test'},async *[Symbol.asyncIterator](){yield Buffer.from(JSON.stringify(body));}});
const response=()=>Object.assign(new EventEmitter(),{destroyed:false});
async function call(service,body){let result;await service(request(body),response(),new URL('http://localhost/api/singing/align?device=cuda'),(code,data)=>result={code,data},'test');return result;}
const params={resourceId:'a'.repeat(64),language:'zh',textVersion:'v1',windows:[{id:'first',from:40,to:49,words:[{id:'a',start:41,end:42}]},{id:'second',from:48,to:55,words:[{id:'b',start:49,end:50}]}]};
async function fixture(){const root=await mkdtemp(path.join(os.tmpdir(),'singing-words-'));await mkdir(path.join(root,'runtime','singing'),{recursive:true});await writeFile(path.join(root,'runtime','singing','ready.json'),JSON.stringify({fingerprints:{model:'first'}}));const directory=path.join(root,'runtime','audio-resources',params.resourceId);await mkdir(directory,{recursive:true});await writeFile(path.join(directory,'metadata.json'),JSON.stringify({audioStart:40,audioEnd:55,source:'vocals'}));await writeFile(path.join(directory,'audio.wav'),'mock');return root;}
test('conditioned requests validate IDs and convert original word seconds to clip seconds',()=>{const request=validateSingingWords(params);assert.equal(request.windows[0].words[0].start,1);assert.equal(request.windows[1].words[0].start,1);assert.throws(()=>validateSingingWords({...params,resourceId:'../bad'}),/无效/);assert.throws(()=>validateSingingWords({...params,windows:[{...params.windows[0],words:[{id:'a',start:0,end:1}]}]}),/超出/);assert.throws(()=>validateSingingWords({...params,windows:[params.windows[0],params.windows[0]]}),/重复/);});
test('conditioned batch runs one process, reports progress, and caches by text, timing and model',async()=>{
 const root=await fixture();let count=0,captured,progress;let service;
 service=singingService(root,{spawnImpl:(python,args)=>{count++;const child=Object.assign(new EventEmitter(),{stdout:new PassThrough(),stderr:new PassThrough()});setImmediate(async()=>{try{captured=JSON.parse(await readFile(args[2],'utf8'));assert.equal(args[1],'--request');child.stdout.write(JSON.stringify({stage:'分音','progress':.5})+'\n');await service({method:'GET',headers:{'x-studio-token':'test'}},response(),new URL('http://localhost/api/singing/status'),(code,data)=>progress=data.job,'test');await writeFile(captured.output,JSON.stringify({windows:captured.windows.map(w=>({id:w.id,events:[],alignedEvents:[],note2words:[]}))}));child.exitCode=0;child.emit('close',0);}catch(error){child.emit('error',error);}});return child;}});
 try{const result=await call(service,params);assert.equal(result.code,200);assert.equal(captured.windows.length,2);assert.equal(captured.origin,40);assert.equal(count,1);assert.deepEqual(progress,{stage:'分音',progress:.5});assert.equal((await call(service,params)).data.cacheHit,true);assert.equal(count,1);await call(service,{...params,textVersion:'v2'});assert.equal(count,2);await call(service,{...params,windows:[{...params.windows[0],words:[{id:'a',start:41.1,end:42}]}]});assert.equal(count,3);await writeFile(path.join(root,'runtime','singing','ready.json'),JSON.stringify({fingerprints:{model:'next'}}));await call(service,params);assert.equal(count,4);assert.equal((await readdir(path.join(root,'runtime','singing'))).some(n=>n.startsWith('task-')),false);const invalid=await call(service,{...params,windows:[{id:'third',from:39,to:42,words:[]}]});assert.equal(invalid.code,400);assert.equal(count,4);}finally{await rm(root,{recursive:true,force:true});}
});
test('cancelled conditioned process cleans temporary clips and allows a later request',async()=>{
 const root=await fixture();let started,release;const gate=new Promise(r=>started=r);
 const service=singingService(root,{spawnImpl:()=>{const child=Object.assign(new EventEmitter(),{stdout:new PassThrough(),stderr:new PassThrough(),kill(){this.exitCode=1;this.emit('close',1);}});started();return child;}});
 try{const res=response();let result;const pending=service(request(params),res,new URL('http://localhost/api/singing/align'),(code,data)=>result={code,data},'test');await gate;assert.equal(service.busy(),true);const concurrent=await call(service,params);assert.equal(concurrent.code,409);assert.equal(service.busy(),true);res.emit('close');await pending;assert.equal(result.code,400);assert.match(result.data.error,/取消/);assert.equal(service.busy(),false);assert.equal((await readdir(path.join(root,'runtime','singing'))).some(n=>n.startsWith('task-')),false);}finally{await rm(root,{recursive:true,force:true});}
});
